Added enemy drops and mana potions
AndreiBaetica/Dungeoneer pull request #228
Opened 2021-11-30 02:37 UTC by SebastienGorman

Added mana potions
Fixed bug with enemy drop pouches not being looted properly with stacked items
Enemies now drop a pouch containing 1 hp and 3 mana potions

2021-11-30 03:34 UTC, AndreiBaetica commented on Assets/Scripts/Inventory/LootableScript.cs
> +        /*if (Input.GetKeyDown(KeyCode.O))
let's delete this entirely

2021-11-30 03:44 UTC, AndreiBaetica requested changes
bug - all corpses share the same inventory

2021-12-01 00:14 UTC, RossBaumgartner approved these changes
tested and working

2021-12-01 00:18 UTC, AndreiBaetica approved these changes
LGTM

2021-12-01 00:21 UTC, merged