Enemy ai
AndreiBaetica/Dungeoneer pull request #57
Opened 2021-03-16 23:09 UTC by chern042

Basic movement system added for enemy with a NavMeshAgent as the AI after turning the enemy and player objects into separate Enemy and PlayerManager scripts to keep track of Player and Enemy stats. I also have a separate PlayerController and EnemyController to control their movement.

2021-03-17 21:08 UTC, AndreiBaetica requested changes
Not approving yet, on account of a bug that causes the NPC's X and Z coordinates to offset into decimals over time.

2021-03-17 21:08 UTC, AndreiBaetica commented on Assets/Scripts/Controllers/EnemyController.cs
> +    void Update()
Since these are duplicates of the methods in PlayerController, let's abstract these to a MovementController class.

2021-03-17 21:08 UTC, AndreiBaetica commented on Assembly-CSharp.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Make sure to git rm this file before merging. It's part of our gitignore.

2021-03-18 23:57 UTC, AndreiBaetica approved these changes
Should be good to merge now. AI takes a slight detour when going from attack state to chase state. Not critical.

I know the cause of this and it's a simple fix, but let's get this into master first and I'll have a separate PR for that fix.

2021-03-19 03:07 UTC, RossBaumgartner commented on Assets/Scripts/Controllers/EnemyController.cs
> +            /*float distance = Vector3.Distance(target.position, transform.position);
these comments should be cleaned up later on

2021-03-19 03:08 UTC, RossBaumgartner approved these changes
needs a bit of cleaning (commented code) and documenetation maybe. 
otherwise looks good and works properly

2021-03-19 03:39 UTC, AndreiBaetica commented
> needs a bit of cleaning (commented code) and documenetation maybe.
> otherwise looks good and works properly

Ah yes, good point, going to delete all that now.
As for the documentation, it matches the design docs from yesterday, with the only change being the distance that triggers the attack state. I'll update that tomorrow.

2021-03-20 02:50 UTC, SebastienGorman approved these changes

2021-03-20 02:52 UTC, merged